CREATE TABLE IF NOT EXISTS WALLETS(
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    CPF BIGINT UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    "PASSWORD" VARCHAR(100),
    "TYPE" INT,
    BALANCE DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS(
    ID SERIAL PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    "VALUE" DECIMAL(10,2),
    CREATED_AT TIMESTAMP,

    FOREIGN KEY (PAYER) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS(ID)
)
