CREATE TABLE IF NOT EXISTS wallets(
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    CPF BIGINT UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    "password" VARCHAR(100),
    "type" INT,
    BALANCE DECIMAL(10,2),
    CREDIT DECIMAL(10,2),
    "blocked" BOOLEAN
);

CREATE TABLE IF NOT EXISTS transactions(
    ID SERIAL PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    AMOUNT DECIMAL(10,2),
    TYPE_TRANSACTION INT,
    INSTALLMENTS INT,
    CREATED_AT TIMESTAMP,

    FOREIGN KEY (PAYER) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS(ID)
);

CREATE TABLE IF NOT EXISTS transactions_future(
    ID SERIAL PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    AMOUNT DECIMAL(10,2),
    TOTAL_AMOUNT DECIMAL(10,2),
    TYPE_TRANSACTION INT,
    INSTALLMENTS INT,
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP,
    NEXT_PAYMENT TIMESTAMP,

    FOREIGN KEY (PAYER) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS(ID)
);
