CREATE TABLE IF NOT EXISTS users (
    ID UUID UNIQUE PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    "password" VARCHAR(100),
    CPF BIGINT UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    "type" INT NOT NULL,
    "role" VARCHAR(50) NOT NULL,
    "wallet_id" UUID UNIQUE
);
CREATE TABLE IF NOT EXISTS wallets (
    ID UUID UNIQUE PRIMARY KEY,
    "type" INT,
    BALANCE DECIMAL(10,2),
    CREDIT DECIMAL(10,2),
    IS_BLOCKED BOOLEAN,
    "user_id" UUID UNIQUE,

    FOREIGN KEY ("user_id") REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS transactions_future(
    ID UUID UNIQUE PRIMARY KEY,
    TOTAL_AMOUNT DECIMAL(10,2),
    IS_ACTIVE BOOLEAN,
    NUMBER_OF_INSTALLMENTS INT,
    NEXT_PAYMENT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions(
    ID UUID UNIQUE PRIMARY KEY,
    PAYER_ID UUID NOT NULL,
    PAYEE_ID UUID NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    TYPE_TRANSACTION INT NOT NULL,
    INSTALLMENTS INT NOT NULL,
    CREATED_AT TIMESTAMP,
    TRANSACTION_FUTURE UUID,

    FOREIGN KEY (PAYER_ID) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE_ID) REFERENCES WALLETS(ID),
    FOREIGN KEY (TRANSACTION_FUTURE) REFERENCES transactions_future(ID)
);





